### ISSUE TITLE
Crashing on 10.8.5

### ISSUE THREAD

**Issue by bunk3m** [jaredsburrows/Rarcrack#1]
Been trying to unlock a rar file.  rarcrack crashes about 15-20 mins after starting.  (I figured out today that the rar file has been corrupted so part of this problem is about a bad rar file.  However, it would be nice if rarcrack would exit gracefully??)

I moved rarcrack to /usr/local/bin  and set as 755 with root and wheel as user and group respectively.

Hope the following helps make it better.  BTW, thanks for fixing up to run on OSX!!

Details from crash reporter below:
Process:         rarcrack [929]
Path:            /usr/local/bin/rarcrack
Identifier:      rarcrack
Version:         0
Code Type:       X86-64 (Native)
Parent Process:  bash [416]
User ID:         501

Date/Time:       2014-01-26 14:38:18.828 -0500
OS Version:      Mac OS X 10.8.5 (12F45)
Report Version:  10

Interval Since Last Report:          5410 sec
Crashes Since Last Report:           1
Per-App Crashes Since Last Report:   1

Crashed Thread:  2

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: EXC_I386_GPFLT

Thread 0:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff8696d386 __semwait_signal + 10
1   libsystem_c.dylib             	0x00007fff86f93c85 pthread_join + 847
2   rarcrack                      	0x0000000103d0ee3a crack_start + 138
3   rarcrack                      	0x0000000103d0f3b2 init + 1314
4   rarcrack                      	0x0000000103d0f402 main + 34
5   libdyld.dylib                 	0x00007fff8f7317e1 start + 1

Thread 1:
0   libsystem_kernel.dylib        	0x00007fff8696d06e __posix_spawn + 10
1   libsystem_c.dylib             	0x00007fff86f3250e posix_spawn + 242
2   libsystem_c.dylib             	0x00007fff86f5c6e8 popen + 559
3   rarcrack                      	0x0000000103d0ecd0 crack_thread + 144
4   libsystem_c.dylib             	0x00007fff86f09772 _pthread_start + 327
5   libsystem_c.dylib             	0x00007fff86ef61a1 thread_start + 13

Thread 2 Crashed:
0   libsystem_c.dylib             	0x00007fff86f5c687 popen + 462
1   rarcrack                      	0x0000000103d0ecd0 crack_thread + 144
2   libsystem_c.dylib             	0x00007fff86f09772 _pthread_start + 327
3   libsystem_c.dylib             	0x00007fff86ef61a1 thread_start + 13

Thread 3:
0   libsystem_kernel.dylib        	0x00007fff8696d386 __semwait_signal + 10
1   libsystem_c.dylib             	0x00007fff86f937c8 nanosleep + 163
2   libsystem_c.dylib             	0x00007fff86f93652 sleep + 61
3   rarcrack                      	0x0000000103d0ec00 status_thread + 176
4   libsystem_c.dylib             	0x00007fff86f09772 _pthread_start + 327
5   libsystem_c.dylib             	0x00007fff86ef61a1 thread_start + 13

Thread 2 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0xf000000000000000  rcx: 0x00007fa01c004000  rdx: 0x0000000000000004
  rdi: 0x00000001040eebf8  rsi: 0x0000000000000004  rbp: 0x00000001040eec60  rsp: 0x00000001040eebe0
   r8: 0x0000000000000045   r9: 0x0000000000000000  r10: 0x0000000000008a00  r11: 0x0000000000000044
  r12: 0x00007fa01b500000  r13: 0x00000001040eebf8  r14: 0x0000000103d0f7a8  r15: 0x00007fff743da138
  rip: 0x00007fff86f5c687  rfl: 0x0000000000010286  cr2: 0x00007fff748e5ff0
Logical CPU: 1

Binary Images:
       0x103d0d000 -        0x103d0fff7 +rarcrack (0) <B1324293-4C93-3967-9EDD-859DADF503A5> /usr/local/bin/rarcrack
       0x103d14000 -        0x103e48ff7 +libxml2.2.dylib (0) <BA02B6FE-43BC-31BD-BD10-ADCF6D44E1F4> /opt/local/lib/libxml2.2.dylib
       0x103e7d000 -        0x103e8efff +libz.1.dylib (0) <A9EB10A3-B238-3A9B-B23A-7FB5F5C9685E> /opt/local/lib/libz.1.dylib
       0x103e93000 -        0x103f8bff7 +libiconv.2.dylib (0) <1914316E-52FA-3DC3-9CE7-6D2D71CFD4DB> /opt/local/lib/libiconv.2.dylib
       0x103f9a000 -        0x103fb7fff +liblzma.5.dylib (0) <1B2F98A0-2B38-3F72-B73F-0518C5377F6B> /opt/local/lib/liblzma.5.dylib
    0x7fff6390d000 -     0x7fff6394193f  dyld (210.2.3) <36CAA36E-72BC-3E48-96D9-B96A2DF77730> /usr/lib/dyld
    0x7fff84cdc000 -     0x7fff84df492f  libobjc.A.dylib (532.2) <90D31928-F48D-3E37-874F-220A51FD9E37> /usr/lib/libobjc.A.dylib
    0x7fff84f6e000 -     0x7fff84f70fff  libquarantine.dylib (52.1) <143B726E-DF47-37A8-90AA-F059CFD1A2E4> /usr/lib/system/libquarantine.dylib
    0x7fff8500e000 -     0x7fff8500fff7  libsystem_sandbox.dylib (220.3) <B739DA63-B675-387A-AD84-412A651143C0> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff85224000 -     0x7fff85270ff7  libauto.dylib (185.4) <AD5A4CE7-CB53-313C-9FAE-673303CC2D35> /usr/lib/libauto.dylib
    0x7fff8695b000 -     0x7fff86976ff7  libsystem_kernel.dylib (2050.48.12) <4B7993C3-F62D-3AC1-AF92-414A0D6EED5E> /usr/lib/system/libsystem_kernel.dylib
    0x7fff86ef5000 -     0x7fff86fc1ff7  libsystem_c.dylib (825.40.1) <543B05AE-CFA5-3EFE-8E58-77225411BA6B> /usr/lib/system/libsystem_c.dylib
    0x7fff87877000 -     0x7fff87879ff7  libunc.dylib (25) <92805328-CD36-34FF-9436-571AB0485072> /usr/lib/system/libunc.dylib
    0x7fff87d81000 -     0x7fff87d81fff  libkeymgr.dylib (25) <CC9E3394-BE16-397F-926B-E579B60EE429> /usr/lib/system/libkeymgr.dylib
    0x7fff890c5000 -     0x7fff890c6fff  libsystem_blocks.dylib (59) <D92DCBC3-541C-37BD-AADE-ACC75A0C59C8> /usr/lib/system/libsystem_blocks.dylib
    0x7fff89b3f000 -     0x7fff89b46fff  libcopyfile.dylib (89) <876573D0-E907-3566-A108-577EAD1B6182> /usr/lib/system/libcopyfile.dylib
    0x7fff89c82000 -     0x7fff89cb0ff7  libsystem_m.dylib (3022.6) <B434BE5C-25AB-3EBD-BAA7-5304B34E3441> /usr/lib/system/libsystem_m.dylib
    0x7fff89cff000 -     0x7fff89d04fff  libcompiler_rt.dylib (30) <08F8731D-5961-39F1-AD00-4590321D24A9> /usr/lib/system/libcompiler_rt.dylib
    0x7fff89d65000 -     0x7fff89d70fff  libsystem_notify.dylib (98.5) <C49275CC-835A-3207-AFBA-8C01374927B6> /usr/lib/system/libsystem_notify.dylib
    0x7fff89dab000 -     0x7fff89dfaff7  libcorecrypto.dylib (106.2) <CE0C29A3-C420-339B-ADAA-52F4683233CC> /usr/lib/system/libcorecrypto.dylib
    0x7fff8a279000 -     0x7fff8a287ff7  libsystem_network.dylib (77.10) <0D99F24E-56FE-380F-B81B-4A4C630EE587> /usr/lib/system/libsystem_network.dylib
    0x7fff8a302000 -     0x7fff8a36aff7  libc++.1.dylib (65.1) <20E31B90-19B9-3C2A-A9EB-474E08F9FE05> /usr/lib/libc++.1.dylib
    0x7fff8b177000 -     0x7fff8b17fff7  libsystem_dnssd.dylib (379.38.1) <BDCB8566-0189-34C0-9634-35ABD3EFE25B> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff8be14000 -     0x7fff8be22fff  libcommonCrypto.dylib (60027) <BAAFE0C9-BB86-3CA7-88C0-E3CBA98DA06F> /usr/lib/system/libcommonCrypto.dylib
    0x7fff8c0cc000 -     0x7fff8c0d4fff  liblaunch.dylib (442.26.2) <2F71CAF8-6524-329E-AC56-C506658B4C0C> /usr/lib/system/liblaunch.dylib
    0x7fff8c150000 -     0x7fff8c151ff7  libremovefile.dylib (23.2) <6763BC8E-18B8-3AD9-8FFA-B43713A7264F> /usr/lib/system/libremovefile.dylib
    0x7fff8e716000 -     0x7fff8e71bfff  libcache.dylib (57) <65187C6E-3FBF-3EB8-A1AA-389445E2984D> /usr/lib/system/libcache.dylib
    0x7fff8eca3000 -     0x7fff8eca9ff7  libunwind.dylib (35.1) <21703D36-2DAB-3D8B-8442-EAAB23C060D3> /usr/lib/system/libunwind.dylib
    0x7fff8f0f4000 -     0x7fff8f116ff7  libxpc.dylib (140.43) <70BC645B-6952-3264-930C-C835010CCEF9> /usr/lib/system/libxpc.dylib
    0x7fff8f454000 -     0x7fff8f45afff  libmacho.dylib (829) <BF332AD9-E89F-387E-92A4-6E1AB74BD4D9> /usr/lib/system/libmacho.dylib
    0x7fff8f72d000 -     0x7fff8f72eff7  libdnsinfo.dylib (453.19) <14202FFB-C3CA-3FCC-94B0-14611BF8692D> /usr/lib/system/libdnsinfo.dylib
    0x7fff8f72f000 -     0x7fff8f732ff7  libdyld.dylib (210.2.3) <F59367C9-C110-382B-A695-9035A6DD387E> /usr/lib/system/libdyld.dylib
    0x7fff8f733000 -     0x7fff8f748ff7  libdispatch.dylib (228.23) <D26996BF-FC57-39EB-8829-F63585561E09> /usr/lib/system/libdispatch.dylib
    0x7fff8f759000 -     0x7fff8f77eff7  libc++abi.dylib (26) <D86169F3-9F31-377A-9AF3-DB17142052E4> /usr/lib/libc++abi.dylib
    0x7fff8f794000 -     0x7fff8f795ff7  libSystem.B.dylib (169.3) <9089D72D-E714-31E1-80C8-698A8E8B05AD> /usr/lib/libSystem.B.dylib
    0x7fff8fe51000 -     0x7fff8fe87fff  libsystem_info.dylib (406.17) <4FFCA242-7F04-365F-87A6-D4EFB89503C1> /usr/lib/system/libsystem_info.dylib
    0x7fff908cf000 -     0x7fff908d0fff  libDiagnosticMessagesClient.dylib (8) <8548E0DC-0D2F-30B6-B045-FE8A038E76D8> /usr/lib/libDiagnosticMessagesClient.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 1
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 919
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=59.1M resident=37.6M(64%) swapped_out_or_unallocated=21.5M(36%)
Writable regions: Total=28.0M written=268K(1%) resident=360K(1%) swapped_out=0K(0%) unallocated=27.6M(99%)
 
REGION TYPE                      VIRTUAL
===========                      =======
MALLOC                             18.2M
MALLOC guard page                    16K
STACK GUARD                        56.0M
Stack                              9752K
__DATA                              676K
__LINKEDIT                         52.3M
__TEXT                             7008K
shared memory                        12K
===========                      =======
TOTAL                             143.5M

**Comment by jaredsburrows** [comment]
@bunk3m Are you still experiencing this issue?

**Comment by bunk3m** [comment]
Hi @jaredsburrows 

I haven't had the need for using it for some time so I can't say if the issue still exists.

Thanks for keeping me in the loop.

**Comment by jaredsburrows** [comment]
@bunk3m I am really just not seeing this. I have updated the project to use Travis CI.

**Comment by jaredsburrows** [comment]
@bunk3m I am closing this for now. We can open this if you have seen this again.
