### ISSUE TITLE
Cannot execute `make` on OS X

### ISSUE THREAD

**Issue by iampomelo** [jaredsburrows/rarcrack#15]
gcc -pthread rarcrack.c `xml2-config --libs --cflags` -O3 -o rarcrack
rarcrack.c:226:1: warning: control reaches end of non-void function [-Wreturn-type]
}
^
rarcrack.c:262:1: warning: control reaches end of non-void function [-Wreturn-type]
}
^
2 warnings generated.

**Comment by jaredsburrows** [comment]
I worked on this on Mac OSX.

After running make, you can now run `rarcrack`:
```
$ ./rarcrack 
RarCrack! 0.2 by David Zoltan Kedves (kedazo@gmail.com)

USAGE: rarcrack encrypted_archive.ext [--threads NUM] [--type rar|zip|7z]
       For more information please run "rarcrack --help"
```
