### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by soniktrooth** [jaredsburrows/rarcrack#16]
I'm getting this error: 
`-c: line 0: syntax error near unexpected token '('`

**Comment by jaredsburrows** [comment]
Can you give me more information? And a repro?

**Comment by soniktrooth** [comment]
Actually I was able to get it working by moving the file to a different location. Perhaps it was because of spaces in folder names?

**Comment by jaredsburrows** [comment]
Maybe. How did the command look? Do you have an example? You should be using quotes via command line.
