### ISSUE TITLE
type autodetect don't work

### ISSUE THREAD

**Issue by davidak** [jaredsburrows/Rarcrack#2]
i don't know where the hard coded mime types come from but i get different ones on current systems.

https://github.com/jaredsburrows/Rarcrack/blob/master/rarcrack.c#L26
`const char *MIME[] = { "application/x-rar", "application/octet-stream", "application/x-zip", "" };`

Ubuntu 14.04 LTS
```
# file --version
file-5.14
~/rarcrack-0.2# file -i -b test.rar
application/x-rar; charset=binary
~/rarcrack-0.2# file -i -b test.7z
application/x-7z-compressed; charset=binary
~/rarcrack-0.2# file -i -b test.zip
application/zip; charset=binary
```

NixOS 15.09
```
$ file --version
file-5.25
$ file -i -b test.rar 
application/x-rar; charset=binary
[davidak@nixos:~/Downloads/rarcrack-0.2]$ file -i -b test.7z 
application/x-7z-compressed; charset=binary
[davidak@nixos:~/Downloads/rarcrack-0.2]$ file -i -b test.zip 
application/zip; charset=binary

```

OS X 10.10:
```
$ file --version
file-5.04
```
always `regular file`

as i understand, it compares the whole string and not just the start, so there should be the whole string posted above.
i tried to replace them but it didn't work. still

```
INFO: detected file type: 
ERROR: Couldn't detect archive type
```

**Comment by jaredsburrows** [comment]
@davidak This is a port to OSX. Does it work fine on OSX?

**Comment by davidak** [comment]
I have only tried Linux. The Readme says that it works on Linux. What Version have you tested?

**Comment by davidak** [comment]
So i debugged it the last hours and found out, that `test` in https://github.com/jaredsburrows/Rarcrack/blob/master/rarcrack.c#L450 has the value "application/x-rar;" at runtime.

So if anyone wants to run this with newer versions of file, just replace the Types like i did in my Nix Package: https://github.com/NixOS/nixpkgs/pull/12491 (see substituteInPlace in package definition)

**Comment by jaredsburrows** [comment]
@davidak Good eye. Could you submit a PR for this? I'll merge #2.

**Comment by davidak** [comment]
yes, fix is now also in that PR. thank you :)
