### ISSUE TITLE
Segmentation fault.

### ISSUE THREAD

**Issue by zhenpingfeng** [jaredsburrows/rarcrack#5]
Running on OS X 10.10.5

./rarcrack --threads 6 --type rar a.rar
RarCrack! 0.2 by David Zoltan Kedves (kedazo@gmail.com)

INFO: the specified archive type: rar
INFO: cracking a.rar, status file: a.rar.xml
Probing: '05J' [1418 pwds/sec]
Probing: '1cJ' [1426 pwds/sec]
Probing: '2mE' [1486 pwds/sec]
Probing: '3y0' [1516 pwds/sec]
Probing: '4IJ' [1503 pwds/sec]
Probing: '5RH' [1466 pwds/sec]
Probing: '6ZX' [1452 pwds/sec]
[1]    77928 segmentation fault  ./rarcrack --threads 6 --type rar a.rar

**Comment by zhaochl** [comment]
RarCrack! 0.2 by David Zoltan Kedves (kedazo@gmail.com)

INFO: the specified archive type: rar
INFO: cracking t.rar, status file: t.rar.xml
INFO: Resuming cracking from password: 'jkp'
Probing: 'jUu' [743 pwds/sec]
Probing: 'ktP' [730 pwds/sec]
Probing: 'l3K' [742 pwds/sec]
Probing: 'lEj' [755 pwds/sec]
Probing: 'me9' [740 pwds/sec]
Probing: 'mNl' [727 pwds/sec]
Segmentation fault: 11

**Comment by jaredsburrows** [comment]
Try only using 3 threads. It seems like sometimes increasing the number of threads causes a `segmentation fault`.

**Comment by jaredsburrows** [comment]
Any update on this?

**Comment by piotrekkmt** [comment]
Getting this too. Anybody knows how to fix this? Since we're making the file, might as well fix a bit of code

**Comment by shivanraptor** [comment]
This critical issue is random when threads are more than 1.

**Comment by MahdiPishguy** [comment]
also i get i get this error too

```zsh
zsh: segmentation fault  ./rarcrack --threads 2 --type rar test.rar
```

**Comment by kotielnikov-s-massmediagroup** [comment]
the same thing on mac os. consider using supervisor to revive the process every time it fails

**Comment by ubudragon** [comment]
1 thread is too slow
